# Generated by Django 5.1.1 on 2024-09-28 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("useraccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="backend_userprofile",
        ),
    ]
